# Generated by Django 3.2.7 on 2021-10-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_student_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
