# Generated by Django 3.2.7 on 2021-10-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_createbook_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='docfile',
            field=models.CharField(max_length=50),
        ),
    ]
