# Generated by Django 3.2.7 on 2021-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_createbook_docfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(upload_to='files/%Y/%m/%d/'),
        ),
    ]
