# Generated by Django 3.2.7 on 2021-10-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
