# Generated by Django 3.2.7 on 2021-10-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_createbook_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='docfile',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
