# Generated by Django 3.2.7 on 2021-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211015_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbook',
            name='docfile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createbook',
            name='img',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
